services:
  my-server:
    build:
      context: ./website
    restart: always
    environment:
      VIRTUAL_HOST: v4.mader.xyz, v4.mader.lo
      LETSENCRYPT_HOST: v4.mader.xyz
      LETSENCRYPT_EMAIL: vincent.mader@icloud.com
    ports:
      - 8001:8000
    volumes: 
      - database:/var/www/sono-server/database
    networks:
      - reverse-proxy

volumes:
  database:
    external: false

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in `./proxy/docker-compose.yml`.
    #   Additionally, it it prefixed by the proxy directory name (see "docker network ls").

