#+TITLE: mader.xyz
#+AUTHOR: Vincent C. Mader

This repo contains the code running [[http://mader.xyz][my website]].

* Installation
To contribute, you'll need to install the server locally via the following steps:

- Make sure you have python3+pip and nodejs+npm installed
- Download the repo
#+begin_src shell
git clone https://github.com/vincentmader/mader.xyz
cd mader.xyz
#+end_src
- Create a virtual python environment & source it
#+begin_src shell
python -m venv venv
source venv/bin/activate
#+end_src
- Install python dependencies
#+begin_src shell
pip3 install -r requirements.txt
#+end_src
- Navigate into the frontend code and install js dependencies
#+begin_src shell
cd FlaskApp/static/js/react_frontend
npm install
#+end_src
- Test-run the server
#+begin_src shell
cd FlaskApp
python3 __init__.py
#+end_src
- Open your browser and head to [[http://localhost:5000][localhost:5000] to check if it works.
  If not, continue with the next section and try again afterwards.
* Basic setup
After completing the installation, you should take a look at the file
#+begin_src shell
./FlaskApp/config.py
#+end_src
and initialize the path variables.
# * Further steps
# You may also need to create the file
# #+begin_src shell
# ./.env
# #+end_src
# and define your application secret key (used for encryption).
# This file is loaded from
# #+begin_src shell
# ./flaskapp.wsgi
# #+end_src
# and should look like this:
# #+begin_src shell
# SECRET_KEY="<your secret key goes here>"
# #+end_src
