[package]
    name = "maderxyz-simulations"
    version = "0.1.0"
    edition = "2021"

[features]
    default = ["console_error_panic_hook"]

[dependencies]
    wasm-bindgen = "0.2.78"
    console_error_panic_hook = { version = "0.1.6", optional = true }
