[package]
    name = "maderxyz-database"
    version = "0.1.0"
    authors = ["Vincent C. Mader <vincent.mader@icloud.com>"]
    edition = "2018"

[dependencies]
    diesel = { version = "1.4.4", features = ["postgres"] }
    dotenv = "0.15.0"
