#!/bin/sh

cd `dirname "$0"`
cd ../maderxyz-client

cargo build  # --release
wasm-bindgen --target web --out-dir ../maderxyz-server/static/pkg ../target/wasm32-unknown-unknown/debug/maderxyz_frontend.wasm
