#!/usr/bin/sh

apt update
apt upgrade

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
apt install -y cargo, nodejs, nginx
apt install -y libssl-dev, pkg-config
cargo install -f wasm-bindgen-cli

# rustup
# cargo
# nginx -h

# /etc/nginx/sites-available/mader.xyz.tld.conf
# server {
#     listen 80;
#     listen [::]:80;
# 
#     server_name mader.xyz www.mader.xyz;
# 
#     location / {
#         proxy_pass http://0.0.0.0:8000;
#         proxy_buffering off;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }

nginx -t
cd /etc/nginx && ln -s sites-available/mader.xyz.tld.conf sites-enabled/mader.xyz.tld.conf

# /etc/systemd/system/mader.xzy.tld.service
# [Unit]
# Description=mader.xyz
# 
# [Service]
# User=www-data
# Group=www-data
# WorkingDirectory=/home/root/mader.xyz/
# Environment="ROCKET_ENV=prod"
# Environment="ROCKET_ADDRESS=0.0.0.0"
# Environment="ROCKET_PORT=8000"
# Environment="ROCKET_LOG=critial"
# ExecStart=/home/root/mader.xyz/target/release/maderxyz-server
# 
# [Install]
# WantedBy=multi-user.target

systemctl start mader.xyz.tld.service
systemctl enable mader.xyz.tld.service  # TODO needed after ln -s?
